import api from './http'

export interface AiChatMessage {
  role: 'user' | 'assistant' | 'system'
  content: string
}

export interface SkillTemplate {
  id?: number
  name: string
  description?: string
  category: string
  flowDefinitionJson?: string
  sourceType?: string
  targetType?: string
  tags?: string
  usageCount?: number
  successRate?: number
  sourceFlowId?: number
  autoGenerated?: boolean
  createdAt?: string
  updatedAt?: string
}

export interface UserPreference {
  id?: number
  preferenceType: string
  preferenceKey: string
  preferenceValue?: string
  frequency?: number
  lastUsedAt?: string
}

export interface AiFlowResult {
  success: boolean
  message: string
  flowDefinition?: any
  aiResponse?: string
}

const AI_TIMEOUT = 120000

export const aiApi = {
  chat(message: string, history: AiChatMessage[] = []) {
    return api.post<any, { message: string }>('/ai/chat', { message, history }, { timeout: AI_TIMEOUT })
  },

  generateFlow(requirement: string, autoSave = false) {
    return api.post<any, AiFlowResult>('/ai/generate-flow', { requirement, autoSave: String(autoSave) }, { timeout: AI_TIMEOUT })
  },

  analyze(requirement: string) {
    return api.post<any, { analysis: string }>('/ai/analyze', { requirement }, { timeout: AI_TIMEOUT })
  },

  getSkills(category?: string) {
    const params = category ? { category } : {}
    return api.get<any, SkillTemplate[]>('/ai/skills', { params })
  },

  createSkill(skill: SkillTemplate) {
    return api.post<any, SkillTemplate>('/ai/skills', skill)
  },

  updateSkill(id: number, skill: SkillTemplate) {
    return api.put<any, SkillTemplate>(`/ai/skills/${id}`, skill)
  },

  deleteSkill(id: number) {
    return api.delete(`/ai/skills/${id}`)
  },

  incrementSkillUsage(id: number) {
    return api.post(`/ai/skills/${id}/use`)
  },

  getPreferences(type?: string) {
    const params = type ? { type } : {}
    return api.get<any, UserPreference[]>('/ai/preferences', { params })
  },

  learnFromFlow(flowDefinitionId: number, flowName: string) {
    return api.post(`/ai/learn/${flowDefinitionId}`, null, { params: { flowName } })
  },

  getConfig() {
    return api.get<any, { enabled: boolean; model: string; apiUrl: string }>('/ai/config')
  },
}
