package com.migration.ai;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@Table(name = "skill_template")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class SkillTemplate {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String name;

    private String description;

    @Column(nullable = false)
    private String category;

    @Column(columnDefinition = "TEXT")
    private String flowDefinitionJson;

    private String sourceType;

    private String targetType;

    @Column(columnDefinition = "TEXT")
    private String tags;

    @Column(nullable = false)
    @Builder.Default
    private Integer usageCount = 0;

    @Column(nullable = false)
    @Builder.Default
    private Double successRate = 0.0;

    private Long sourceFlowId;

    @Builder.Default
    private Boolean autoGenerated = true;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;
}
