package com.migration.ai;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SkillTemplateRepository extends JpaRepository<SkillTemplate, Long> {

    List<SkillTemplate> findByCategoryOrderByUsageCountDesc(String category);

    List<SkillTemplate> findBySourceTypeAndTargetTypeOrderByUsageCountDesc(String sourceType, String targetType);

    List<SkillTemplate> findByAutoGeneratedTrueOrderByUsageCountDesc();

    List<SkillTemplate> findAllByOrderByUsageCountDesc();

    List<SkillTemplate> findByNameContainingIgnoreCase(String keyword);
}
