package com.migration.ai;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.migration.model.dto.FlowDefinitionDTO;
import com.migration.model.entity.FlowNode;
import com.migration.model.enums.NodeType;
import com.migration.repository.FlowNodeRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@Slf4j
@Service
@RequiredArgsConstructor
public class SkillService {

    private final SkillTemplateRepository skillTemplateRepository;
    private final UserPreferenceRepository userPreferenceRepository;
    private final FlowNodeRepository flowNodeRepository;
    private final ObjectMapper objectMapper;

    public void learnFromSuccessfulFlow(Long flowDefinitionId, String flowName) {
        try {
            List<FlowNode> nodes = flowNodeRepository.findByFlowDefinitionIdOrderBySortOrder(flowDefinitionId);
            if (nodes.isEmpty()) return;

            String sourceType = extractSourceType(nodes);
            String targetType = extractTargetType(nodes);
            String category = determineCategory(nodes);

            FlowDefinitionDTO flowDTO = buildFlowDTO(flowDefinitionId, flowName, nodes);
            String flowJson = objectMapper.writeValueAsString(flowDTO);

            String tags = extractTags(nodes);

            SkillTemplate skill = SkillTemplate.builder()
                    .name(flowName)
                    .description("从成功执行的流程自动学习: " + flowName)
                    .category(category)
                    .flowDefinitionJson(flowJson)
                    .sourceType(sourceType)
                    .targetType(targetType)
                    .tags(tags)
                    .usageCount(1)
                    .successRate(100.0)
                    .sourceFlowId(flowDefinitionId)
                    .autoGenerated(true)
                    .createdAt(LocalDateTime.now())
                    .updatedAt(LocalDateTime.now())
                    .build();

            skillTemplateRepository.save(skill);
            log.info("从成功流程学习Skill: flowId={}, category={}", flowDefinitionId, category);

            for (FlowNode node : nodes) {
                learnNodePreferences(node);
            }

        } catch (Exception e) {
            log.error("学习流程失败: flowId={}, error={}", flowDefinitionId, e.getMessage(), e);
        }
    }

    public void recordPreference(String type, String key, String value) {
        try {
            Optional<UserPreference> existing = userPreferenceRepository.findByPreferenceTypeAndPreferenceKey(type, key);
            if (existing.isPresent()) {
                UserPreference pref = existing.get();
                pref.setFrequency(pref.getFrequency() + 1);
                pref.setPreferenceValue(value);
                pref.setLastUsedAt(LocalDateTime.now());
                userPreferenceRepository.save(pref);
            } else {
                UserPreference pref = UserPreference.builder()
                        .preferenceType(type)
                        .preferenceKey(key)
                        .preferenceValue(value)
                        .frequency(1)
                        .lastUsedAt(LocalDateTime.now())
                        .build();
                userPreferenceRepository.save(pref);
            }
        } catch (Exception e) {
            log.error("记录偏好失败: type={}, key={}", type, key, e);
        }
    }

    public List<SkillTemplate> findRelevantSkills(String requirement) {
        List<SkillTemplate> allSkills = skillTemplateRepository.findAllByOrderByUsageCountDesc();
        if (allSkills.isEmpty()) return Collections.emptyList();

        String lowerReq = requirement.toLowerCase();
        List<SkillTemplate> relevant = new ArrayList<>();

        for (SkillTemplate skill : allSkills) {
            boolean match = false;

            if (skill.getTags() != null) {
                String[] tags = skill.getTags().split(",");
                for (String tag : tags) {
                    if (lowerReq.contains(tag.trim().toLowerCase())) {
                        match = true;
                        break;
                    }
                }
            }

            if (skill.getSourceType() != null && lowerReq.contains(skill.getSourceType().toLowerCase())) {
                match = true;
            }
            if (skill.getTargetType() != null && lowerReq.contains(skill.getTargetType().toLowerCase())) {
                match = true;
            }
            if (skill.getName() != null && lowerReq.contains(skill.getName().toLowerCase())) {
                match = true;
            }
            if (skill.getCategory() != null && lowerReq.contains(skill.getCategory().toLowerCase())) {
                match = true;
            }

            if (match) {
                relevant.add(skill);
            }
        }

        return relevant.stream()
                .limit(5)
                .collect(Collectors.toList());
    }

    public List<UserPreference> getTopPreferences(String type, int limit) {
        List<UserPreference> prefs = userPreferenceRepository.findByPreferenceTypeOrderByFrequencyDesc(type);
        return prefs.stream().limit(limit).collect(Collectors.toList());
    }

    public List<SkillTemplate> getAllSkills() {
        return skillTemplateRepository.findAllByOrderByUsageCountDesc();
    }

    public List<SkillTemplate> getSkillsByCategory(String category) {
        return skillTemplateRepository.findByCategoryOrderByUsageCountDesc(category);
    }

    public SkillTemplate createSkill(SkillTemplate skill) {
        skill.setCreatedAt(LocalDateTime.now());
        skill.setUpdatedAt(LocalDateTime.now());
        skill.setAutoGenerated(false);
        if (skill.getUsageCount() == null) skill.setUsageCount(0);
        if (skill.getSuccessRate() == null) skill.setSuccessRate(0.0);
        return skillTemplateRepository.save(skill);
    }

    public SkillTemplate updateSkill(Long id, SkillTemplate updated) {
        SkillTemplate existing = skillTemplateRepository.findById(id).orElse(null);
        if (existing == null) return null;

        if (updated.getName() != null) existing.setName(updated.getName());
        if (updated.getDescription() != null) existing.setDescription(updated.getDescription());
        if (updated.getCategory() != null) existing.setCategory(updated.getCategory());
        if (updated.getFlowDefinitionJson() != null) existing.setFlowDefinitionJson(updated.getFlowDefinitionJson());
        if (updated.getTags() != null) existing.setTags(updated.getTags());
        existing.setUpdatedAt(LocalDateTime.now());

        return skillTemplateRepository.save(existing);
    }

    public void deleteSkill(Long id) {
        skillTemplateRepository.deleteById(id);
    }

    public void incrementUsage(Long id) {
        skillTemplateRepository.findById(id).ifPresent(skill -> {
            skill.setUsageCount(skill.getUsageCount() + 1);
            skill.setUpdatedAt(LocalDateTime.now());
            skillTemplateRepository.save(skill);
        });
    }

    public List<UserPreference> getAllPreferences() {
        return userPreferenceRepository.findAllByOrderByFrequencyDesc();
    }

    private void learnNodePreferences(FlowNode node) {
        if (node.getImplementationClass() == null || node.getImplementationClass().isEmpty()) return;

        recordPreference("implementation", node.getNodeType().name() + ":" + node.getImplementationClass(),
                node.getImplementationClass());

        if (node.getConfig() != null && !node.getConfig().isEmpty()) {
            try {
                @SuppressWarnings("unchecked")
                Map<String, Object> config = objectMapper.readValue(node.getConfig(), Map.class);
                if (config.containsKey("connectionId")) {
                    recordPreference("datasource", config.get("connectionId").toString(),
                            node.getNodeType().name());
                }
                if (config.containsKey("table")) {
                    recordPreference("table", config.get("table").toString(),
                            node.getImplementationClass());
                }
            } catch (Exception ignored) {
            }
        }
    }

    private String extractSourceType(List<FlowNode> nodes) {
        return nodes.stream()
                .filter(n -> n.getNodeType() == NodeType.DATA_EXTRACT)
                .map(n -> extractImplShortName(n.getImplementationClass()))
                .findFirst()
                .orElse("unknown");
    }

    private String extractTargetType(List<FlowNode> nodes) {
        return nodes.stream()
                .filter(n -> n.getNodeType() == NodeType.DATA_LOAD)
                .map(n -> extractImplShortName(n.getImplementationClass()))
                .findFirst()
                .orElse("unknown");
    }

    private String determineCategory(List<FlowNode> nodes) {
        boolean hasExtract = nodes.stream().anyMatch(n -> n.getNodeType() == NodeType.DATA_EXTRACT);
        boolean hasTransform = nodes.stream().anyMatch(n -> n.getNodeType() == NodeType.DATA_TRANSFORM);
        boolean hasLoad = nodes.stream().anyMatch(n -> n.getNodeType() == NodeType.DATA_LOAD);
        boolean hasValidation = nodes.stream().anyMatch(n -> n.getNodeType() == NodeType.VALIDATION);
        boolean hasParallel = nodes.stream().anyMatch(n -> n.getNodeType() == NodeType.PARALLEL_GROUP);

        if (hasParallel) return "parallel_migration";
        if (hasValidation && hasTransform) return "quality_aware_migration";
        if (hasTransform) return "transform_migration";
        if (hasExtract && hasLoad) return "simple_migration";
        return "custom";
    }

    private String extractTags(List<FlowNode> nodes) {
        Set<String> tags = new HashSet<>();
        for (FlowNode node : nodes) {
            tags.add(node.getNodeType().getLabel());
            String shortName = extractImplShortName(node.getImplementationClass());
            if (!"unknown".equals(shortName)) {
                tags.add(shortName);
            }
        }
        return String.join(",", tags);
    }

    private String extractImplShortName(String fullClassName) {
        if (fullClassName == null || fullClassName.isEmpty()) return "unknown";
        int lastDot = fullClassName.lastIndexOf('.');
        return lastDot >= 0 ? fullClassName.substring(lastDot + 1) : fullClassName;
    }

    private FlowDefinitionDTO buildFlowDTO(Long flowDefinitionId, String flowName, List<FlowNode> nodes) {
        FlowDefinitionDTO dto = new FlowDefinitionDTO();
        dto.setName(flowName);
        dto.setNodes(nodes.stream().map(n -> {
            FlowDefinitionDTO.NodeDTO nd = new FlowDefinitionDTO.NodeDTO();
            nd.setNodeId(n.getNodeId());
            nd.setNodeType(n.getNodeType().getCode());
            nd.setName(n.getName());
            nd.setDescription(n.getDescription());
            nd.setConfig(n.getConfig());
            nd.setPositionX(n.getPositionX());
            nd.setPositionY(n.getPositionY());
            nd.setImplementationClass(n.getImplementationClass());
            nd.setParentGroupId(n.getParentGroupId());
            return nd;
        }).collect(Collectors.toList()));
        dto.setEdges(new ArrayList<>());
        return dto;
    }
}
