<template>
  <div class="skill-manager">
    <div class="page-header">
      <h1>Skills 管理</h1>
      <p>管理AI自动学习和手动创建的流程模板，提升流程设计效率</p>
    </div>

    <div class="toolbar">
      <div class="toolbar-left">
        <el-input v-model="searchKeyword" placeholder="搜索模板..." style="width: 240px" clearable>
          <template #prefix>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
              <circle cx="11" cy="11" r="8" stroke="currentColor" stroke-width="2"/>
              <line x1="21" y1="21" x2="16.65" y2="16.65" stroke="currentColor" stroke-width="2"/>
            </svg>
          </template>
        </el-input>
        <el-select v-model="filterCategory" placeholder="分类筛选" clearable style="width: 160px">
          <el-option v-for="cat in categories" :key="cat" :label="cat" :value="cat" />
        </el-select>
      </div>
      <div class="toolbar-right">
        <button class="btn primary" @click="showCreateDialog = true">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
            <line x1="12" y1="5" x2="12" y2="19" stroke="currentColor" stroke-width="2"/>
            <line x1="5" y1="12" x2="19" y2="12" stroke="currentColor" stroke-width="2"/>
          </svg>
          创建模板
        </button>
      </div>
    </div>

    <div class="stats-bar">
      <div class="stat-card">
        <div class="stat-value">{{ skills.length }}</div>
        <div class="stat-label">模板总数</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">{{ autoGeneratedCount }}</div>
        <div class="stat-label">自动学习</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">{{ manualCount }}</div>
        <div class="stat-label">手动创建</div>
      </div>
      <div class="stat-card">
        <div class="stat-value">{{ totalUsage }}</div>
        <div class="stat-label">总使用次数</div>
      </div>
    </div>

    <div class="skills-grid">
      <div v-for="skill in filteredSkills" :key="skill.id" class="skill-card">
        <div class="skill-card-header">
          <div class="skill-icon" :class="skill.category">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none">
              <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" stroke="currentColor" stroke-width="2"/>
            </svg>
          </div>
          <div class="skill-badges">
            <span class="badge auto" v-if="skill.autoGenerated">自动学习</span>
            <span class="badge manual" v-else>手动创建</span>
          </div>
        </div>
        <div class="skill-card-body">
          <h3 class="skill-name">{{ skill.name }}</h3>
          <p class="skill-desc">{{ skill.description || '暂无描述' }}</p>
          <div class="skill-meta">
            <span class="meta-item">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" stroke="currentColor" stroke-width="2"/>
              </svg>
              {{ skill.category }}
            </span>
            <span class="meta-item" v-if="skill.sourceType">
              {{ skill.sourceType }} → {{ skill.targetType }}
            </span>
          </div>
          <div class="skill-tags" v-if="skill.tags">
            <span v-for="tag in skill.tags.split(',').slice(0, 4)" :key="tag" class="tag">{{ tag.trim() }}</span>
          </div>
        </div>
        <div class="skill-card-footer">
          <div class="skill-stats">
            <span>使用 {{ skill.usageCount || 0 }} 次</span>
            <span>成功率 {{ skill.successRate || 0 }}%</span>
          </div>
          <div class="skill-actions">
            <button class="action-btn" @click="applySkill(skill)" title="应用到新流程">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <polyline points="20 6 9 17 4 12" stroke="currentColor" stroke-width="2"/>
              </svg>
            </button>
            <button class="action-btn" @click="editSkill(skill)" title="编辑">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" stroke="currentColor" stroke-width="2"/>
                <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" stroke="currentColor" stroke-width="2"/>
              </svg>
            </button>
            <button class="action-btn danger" @click="deleteSkill(skill)" title="删除">
              <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
                <polyline points="3 6 5 6 21 6" stroke="currentColor" stroke-width="2"/>
                <path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" stroke="currentColor" stroke-width="2"/>
              </svg>
            </button>
          </div>
        </div>
      </div>

      <div v-if="filteredSkills.length === 0" class="empty-state">
        <svg width="64" height="64" viewBox="0 0 24 24" fill="none">
          <path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z" stroke="#dcdfe6" stroke-width="1.5"/>
        </svg>
        <p>暂无Skills模板</p>
        <p class="hint">执行成功的流程会自动学习生成模板，也可以手动创建</p>
      </div>
    </div>

    <el-dialog v-model="showCreateDialog" title="创建Skill模板" width="600px">
      <el-form :model="newSkill" label-width="80px">
        <el-form-item label="名称" required>
          <el-input v-model="newSkill.name" placeholder="模板名称" />
        </el-form-item>
        <el-form-item label="分类" required>
          <el-select v-model="newSkill.category" placeholder="选择分类" style="width: 100%">
            <el-option label="简单迁移" value="simple_migration" />
            <el-option label="转换迁移" value="transform_migration" />
            <el-option label="质量迁移" value="quality_aware_migration" />
            <el-option label="并行迁移" value="parallel_migration" />
            <el-option label="自定义" value="custom" />
          </el-select>
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="newSkill.description" type="textarea" :rows="3" placeholder="模板描述" />
        </el-form-item>
        <el-form-item label="流程定义">
          <el-input v-model="newSkill.flowDefinitionJson" type="textarea" :rows="8" placeholder="流程定义JSON（可选）" />
        </el-form-item>
        <el-form-item label="标签">
          <el-input v-model="newSkill.tags" placeholder="标签，逗号分隔" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="showCreateDialog = false">取消</el-button>
        <el-button type="primary" @click="createSkill">创建</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { aiApi, type SkillTemplate } from '../api/ai'

const router = useRouter()
const skills = ref<SkillTemplate[]>([])
const searchKeyword = ref('')
const filterCategory = ref('')
const showCreateDialog = ref(false)
const newSkill = ref<Partial<SkillTemplate>>({
  name: '',
  category: 'simple_migration',
  description: '',
  flowDefinitionJson: '',
  tags: '',
})

const categories = computed(() => {
  const cats = new Set(skills.value.map(s => s.category))
  return Array.from(cats)
})

const filteredSkills = computed(() => {
  let result = skills.value
  if (searchKeyword.value) {
    const kw = searchKeyword.value.toLowerCase()
    result = result.filter(s =>
      s.name.toLowerCase().includes(kw) ||
      (s.description || '').toLowerCase().includes(kw) ||
      (s.tags || '').toLowerCase().includes(kw)
    )
  }
  if (filterCategory.value) {
    result = result.filter(s => s.category === filterCategory.value)
  }
  return result
})

const autoGeneratedCount = computed(() => skills.value.filter(s => s.autoGenerated).length)
const manualCount = computed(() => skills.value.filter(s => !s.autoGenerated).length)
const totalUsage = computed(() => skills.value.reduce((sum, s) => sum + (s.usageCount || 0), 0))

onMounted(() => {
  loadSkills()
})

async function loadSkills() {
  try {
    skills.value = await aiApi.getSkills() as any
  } catch (e) {
    console.error('加载Skills失败', e)
  }
}

async function createSkill() {
  if (!newSkill.value.name || !newSkill.value.category) {
    ElMessage.warning('请填写必填项')
    return
  }
  try {
    await aiApi.createSkill(newSkill.value as SkillTemplate)
    ElMessage.success('创建成功')
    showCreateDialog.value = false
    newSkill.value = { name: '', category: 'simple_migration', description: '', flowDefinitionJson: '', tags: '' }
    loadSkills()
  } catch (e: any) {
    ElMessage.error('创建失败: ' + (e.message || '未知错误'))
  }
}

async function applySkill(skill: SkillTemplate) {
  if (!skill.flowDefinitionJson) {
    ElMessage.warning('该模板没有流程定义数据')
    return
  }
  try {
    const flowData = JSON.parse(skill.flowDefinitionJson)
    if (skill.id) {
      aiApi.incrementSkillUsage(skill.id).catch(() => {})
    }
    router.push({ name: 'FlowDesigner' })
    ElMessage.success('模板已加载，请在画布中查看')
  } catch (e) {
    ElMessage.error('模板数据解析失败')
  }
}

function editSkill(skill: SkillTemplate) {
  newSkill.value = { ...skill }
  showCreateDialog.value = true
}

async function deleteSkill(skill: SkillTemplate) {
  try {
    await ElMessageBox.confirm(`确定删除模板 "${skill.name}" 吗？`, '确认删除', { type: 'warning' })
    if (skill.id) {
      await aiApi.deleteSkill(skill.id)
      skills.value = skills.value.filter(s => s.id !== skill.id)
      ElMessage.success('已删除')
    }
  } catch {}
}
</script>

<style scoped>
.skill-manager {
  max-width: 1200px;
  margin: 0 auto;
  padding: 24px;
}

.page-header {
  margin-bottom: 24px;
}

.page-header h1 {
  font-size: 24px;
  font-weight: 600;
  color: #303133;
  margin-bottom: 8px;
}

.page-header p {
  font-size: 14px;
  color: #909399;
}

.toolbar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
}

.toolbar-left {
  display: flex;
  gap: 12px;
}

.btn {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 8px 16px;
  border-radius: 8px;
  border: 1px solid #dcdfe6;
  background: #fff;
  font-size: 14px;
  color: #606266;
  cursor: pointer;
  transition: all 0.2s;
}

.btn.primary {
  background: linear-gradient(135deg, #667eea, #764ba2);
  color: #fff;
  border: none;
}

.btn.primary:hover {
  opacity: 0.9;
}

.stats-bar {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
  margin-bottom: 24px;
}

.stat-card {
  background: #fff;
  border-radius: 12px;
  padding: 20px;
  text-align: center;
  border: 1px solid #ebeef5;
}

.stat-value {
  font-size: 28px;
  font-weight: 700;
  color: #303133;
}

.stat-label {
  font-size: 13px;
  color: #909399;
  margin-top: 4px;
}

.skills-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(320px, 1fr));
  gap: 16px;
}

.skill-card {
  background: #fff;
  border-radius: 12px;
  border: 1px solid #ebeef5;
  overflow: hidden;
  transition: box-shadow 0.2s;
}

.skill-card:hover {
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.08);
}

.skill-card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 16px 16px 0;
}

.skill-icon {
  width: 36px;
  height: 36px;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
}

.skill-icon.simple_migration { background: #ecf5ff; color: #409eff; }
.skill-icon.transform_migration { background: #fdf6ec; color: #e6a23c; }
.skill-icon.quality_aware_migration { background: #f0f9eb; color: #67c23a; }
.skill-icon.parallel_migration { background: #f4f0ff; color: #9b59b6; }
.skill-icon.custom { background: #f5f7fa; color: #909399; }

.badge {
  font-size: 11px;
  padding: 2px 8px;
  border-radius: 10px;
}

.badge.auto {
  background: #ecf5ff;
  color: #409eff;
}

.badge.manual {
  background: #f0f9eb;
  color: #67c23a;
}

.skill-card-body {
  padding: 12px 16px;
}

.skill-name {
  font-size: 15px;
  font-weight: 600;
  color: #303133;
  margin-bottom: 6px;
}

.skill-desc {
  font-size: 13px;
  color: #909399;
  margin-bottom: 10px;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.skill-meta {
  display: flex;
  gap: 12px;
  font-size: 12px;
  color: #909399;
  margin-bottom: 8px;
}

.meta-item {
  display: flex;
  align-items: center;
  gap: 4px;
}

.skill-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.tag {
  font-size: 11px;
  padding: 2px 8px;
  border-radius: 4px;
  background: #f5f7fa;
  color: #909399;
}

.skill-card-footer {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 12px 16px;
  border-top: 1px solid #ebeef5;
  background: #fafafa;
}

.skill-stats {
  display: flex;
  gap: 12px;
  font-size: 12px;
  color: #909399;
}

.skill-actions {
  display: flex;
  gap: 4px;
}

.action-btn {
  width: 28px;
  height: 28px;
  border-radius: 6px;
  border: none;
  background: #fff;
  color: #606266;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s;
}

.action-btn:hover {
  background: #409eff;
  color: #fff;
}

.action-btn.danger:hover {
  background: #f56c6c;
  color: #fff;
}

.empty-state {
  grid-column: 1 / -1;
  text-align: center;
  padding: 60px 0;
  color: #909399;
}

.empty-state p {
  font-size: 15px;
  margin-top: 12px;
}

.empty-state .hint {
  font-size: 13px;
  margin-top: 8px;
}
</style>
